# Site
repository: iamankitroy/iamankitroy.github.io
favicon: images/chemist.png

# Content configuration version
version: 2

# Personal info
name: Ankit Roy
title: Biochemistry Graduate Researcher
email: ankit.roy@mpi-dortmund.mpg.de
# website: https://github.com/iamankitroy/iamankitroy.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: Anks_8D
github_username:  iamankitroy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: ankit-roy-7b079141
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-2767-1766

# Additional icon links
# additional_links:
# - title: Google Scholar
#  icon: fas fa-globe
#  url: https://scholar.google.com/citations?user=e8lZuhcAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  As a Scientific Researcher with 4+ years of experience in Computational Biology and 4+ years experience in experimental Biochemistry, I strive to make biological systems more quantitative, holistic, predictable, and eventually controllable. My enthusiasm for theoretical and experimental biology drives me to be truly discipline-agnostic and to come up with ideas from multiple paradigms to aid my scientific research.

  Things I currently have the most experience with can be broadly classified into: <mark>Biochemistry</mark>, <mark>TIRF Microscopy</mark> and <mark>Computational Biology</mark>. However, I am always eager to explore new ideas and concepts, which helps me grow both personally and professionally. I enjoy staying adaptable and open-minded in the face of new challenges and opportunities.

content:
  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Max Planck Institute of Molecular Physiology
        link: https://www.mpi-dortmund.mpg.de/research-groups/bieling
        link_text: mpi-dortmund.mpg.de
        sub_title: Ph.D. Candidate
        caption: July 2019 - Present | Peter Bieling Lab
        quote: >
          Regulating Actin Dynamics and Branched Network Nucleation for Force Generation during Cell Protrusions.
        description: | # this will include new lines to allow paragraphs
          When cells move, they extend their membranes into flat protrusions, which are formed as a result of forces generated by an orchestrated process that creates a branched network of actin filaments. My goal is to understand the spatial and temporal mechanisms that regulate this process.

          Supervisor: **Dr. Peter Bieling**

      - layout: left
        title: Indian Institute of Science Education and Research
        link: http://cospi.iiserpune.ac.in/cospi/index.html
        link_text: cospi.iiserpune.ac.in
        sub_title: Research Fellow
        caption: August 2016 - May 2019 | COSPI Lab
        quote: >
          Knowledge-Based Prediction of Protein-Protein Interactions.
        description: | # this will include new lines to allow paragraphs
          Protein-protein interactions are ubiquitous in cells and are responsible for a variety of biological functions, ranging from signal transduction to force generation. However, experimental methods for predicting interacting surfaces and characterising the whole interactome are time consuming, cost prohibitive, and unscalable. In this project, I designed a computational algorithm for predicting protein-protein interactions.

          Supervisor: **Prof. M.S. Madhusudhan**
      
      - layout: left
        title: Indian Institute of Science Education and Research
        link: http://cospi.iiserpune.ac.in/cospi/index.html
        link_text: cospi.iiserpune.ac.in
        sub_title: Master's Dissertation Student
        caption: August 2015 - July 2016 | COSPI Lab
        quote: >
          Protein Structure Modelling of Entire Proteome.
        description: | # this will include new lines to allow paragraphs
          Modelled the protein structures of 53% of the _Plutella xylostella_ proteome (~11,000 proteins) using a custom built automated pipeline for template matching and homology modelling with MODELLER.

          Supervisor: **Prof. M.S. Madhusudhan**

      - layout: left
        title: Institute of Bioinformatics and Biotechnology
        link: http://www.unipune.ac.in/snc/institute_of_bioinformatics_and_biotechnology/
        link_text: unipune.ac.in
        sub_title: Project Student
        caption: July 2013 - August 2014 | Smita Zinjarde Lab
        quote: >
          Characterization of Bioactive Peptide from Soil Bacteria.
        description: | # this will include new lines to allow paragraphs
          Isolated, cloned and characterised a gene encoding an antimicrobial protein BLDZ1 from _Bacillus licheniformis_ D1.

          Supervisor: **Prof. Smita Zinjarde**

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Institute of Bioinformatics and Biotechnology
        caption: 2011 - 2016
        sub_title: M.Sc. Biotechnology
        quote: >
          5 year integrated Master's degree at Savitribai Phule Pune University (formerly known as University of Pune).
        description: | # this will include new lines to allow paragraphs
          Multidisciplinary course with subjects including Physics, Chemistry, Biology, Mathematics and Computer Science.

      - layout: left
        title: Learning Centre
        caption: 2009 - 2011
        sub_title: Biology
        quote: >
          Upcoming
        description: | # this will include new lines to allow paragraphs
          Upcoming

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
