# Site
repository: iamankitroy/iamankitroy.github.io
favicon: images/chemist.png

# Content configuration version
version: 2

# Personal info
name: Ankit Roy
title: Biochemistry Graduate Researcher
email: ankit.roy@mpi-dortmund.mpg.de
# website: https://github.com/iamankitroy/iamankitroy.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: Anks_8D
github_username:  iamankitroy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: ankit-roy-7b079141
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-2767-1766

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fab fa-google
  url: https://scholar.google.com/citations?user=e8lZuhcAAAAJ&hl=en&oi=ao
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  As a Scientific Researcher with 4+ years of experience in Computational Biology and 4+ years experience in experimental Biochemistry, I strive to make biological systems more quantitative, holistic, predictable, and eventually controllable. My enthusiasm for theoretical and experimental biology drives me to be truly discipline-agnostic and to come up with ideas from multiple paradigms to aid my scientific research.

  Things I currently have the most experience with can be broadly classified into: <mark>Biochemistry</mark>, <mark>TIRF Microscopy</mark> and <mark>Computational Biology</mark>. However, I am always eager to explore new ideas and concepts, which helps me grow both personally and professionally. I enjoy staying adaptable and open-minded in the face of new challenges and opportunities.

content:
  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Max Planck Institute of Molecular Physiology
        link: https://www.mpi-dortmund.mpg.de/research-groups/bieling
        link_text: mpi-dortmund.mpg.de
        sub_title: Ph.D. Candidate
        caption: July 2019 - Present | Peter Bieling Lab
        quote: >
          Regulating Actin Dynamics and Branched Network Nucleation for Force Generation during Cell Protrusions.
        description: | # this will include new lines to allow paragraphs
          When cells move, they extend their membranes into flat protrusions, which are formed as a result of forces generated by an orchestrated process that creates a branched network of actin filaments. My goal is to understand the spatial and temporal mechanisms that regulate this process.

          Supervisor: **Dr. Peter Bieling**

      - layout: left
        border: weak
        title: Indian Institute of Science Education and Research
        link: http://cospi.iiserpune.ac.in/cospi/index.html
        link_text: cospi.iiserpune.ac.in
        sub_title: Research Fellow
        caption: August 2016 - May 2019 | COSPI Lab
        quote: >
          Knowledge-Based Prediction of Protein-Protein Interactions.
        description: | # this will include new lines to allow paragraphs
          Protein-protein interactions are ubiquitous in cells and are responsible for a variety of biological functions, ranging from signal transduction to force generation. However, experimental methods for predicting interacting surfaces and characterising the whole interactome are time consuming, cost prohibitive, and unscalable. In this project, I designed a computational algorithm for predicting protein-protein interactions.

          Supervisor: **Prof. M.S. Madhusudhan**
      
      - layout: left
        border: weak
        title: Indian Institute of Science Education and Research
        link: http://cospi.iiserpune.ac.in/cospi/index.html
        link_text: cospi.iiserpune.ac.in
        sub_title: Master's Dissertation Student
        caption: August 2015 - July 2016 | COSPI Lab
        quote: >
          Protein Structure Modelling of Entire Proteome.
        description: | # this will include new lines to allow paragraphs
          Modelled the protein structures of 53% of the _Plutella xylostella_ proteome (~11,000 proteins) using a custom built automated pipeline for template matching and homology modelling with MODELLER.

          Supervisor: **Prof. M.S. Madhusudhan**

      - layout: left
        title: Institute of Bioinformatics and Biotechnology
        link: http://www.unipune.ac.in/snc/institute_of_bioinformatics_and_biotechnology/
        link_text: unipune.ac.in
        sub_title: Project Student
        caption: July 2013 - August 2014 | Smita Zinjarde Lab
        quote: >
          Characterization of Bioactive Peptide from Soil Bacteria.
        description: | # this will include new lines to allow paragraphs
          Isolated, cloned and characterised a gene encoding an antimicrobial protein BLDZ1 from _Bacillus licheniformis_ D1.

          Supervisor: **Prof. Smita Zinjarde**

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border: weak
        title: On and off controls within dynein-dynactin on native cargoes
        link: https://doi.org/10.1073/pnas.2103383118
        link_text: doi.org/10.1073/pnas.2103383118
        additional_links:
          - title: https://doi.org/10.1073/pnas.2103383118
            icon: fas fa-book
            url: https://doi.org/10.1073/pnas.2103383118
        quote: P Sanghavi, P Kumar, <b>A Roy</b>, MS Madhusudhan, R Mallik | Proceedings of the National Academy of Sciences | April 2021
        # description: | # this will include new lines to allow paragraphs
        #   Upcoming

      - layout: top-middle
        border: weak
        title: A knowledge-based scoring function to assess quaternary associations of proteins
        link: https://doi.org/10.1093/bioinformatics/btaa207
        link_text: doi.org/10.1093/bioinformatics/btaa207
        additional_links:
          - title: https://doi.org/10.1093/bioinformatics/btaa207
            icon: fas fa-book
            url: https://doi.org/10.1093/bioinformatics/btaa207
        quote: AS Dhawanjewar*, <b>AA Roy</b>*, MS Madhusudhan | Bioinformatics | June 2020
        # description: | # this will include new lines to allow paragraphs
        #   Upcoming

      - layout: top-middle
        border: weak
        title: Predicting and designing therapeutics against the Nipah virus
        link: https://doi.org/10.1371/journal.pntd.0007419
        link_text: doi.org/10.1371/journal.pntd.0007419
        additional_links:
          - title: https://doi.org/10.1371/journal.pntd.0007419
            icon: fas fa-book
            url: https://doi.org/10.1371/journal.pntd.0007419
        quote: N Sen*, TR Kanitkar*, <b>AA Roy</b>*, N Soni, K Amritkar, S Supekar, S Nair, G Singh, MS Madhusudhan | PLoS Neglected Tropical Diseases | December 2019
        # description: | # this will include new lines to allow paragraphs
        #   Upcoming

      - layout: top-middle
        border: weak
        title: Structural insights of a cellobiose dehydrogenase enzyme from the basidiomycetes fungus <i>Termitomyces clypeatus</i>
        link: https://doi.org/10.1016/j.compbiolchem.2019.05.013
        link_text: doi.org/10.1016/j.compbiolchem.2019.05.013
        additional_links:
          - title: https://doi.org/10.1016/j.compbiolchem.2019.05.013
            icon: fas fa-book
            url: https://doi.org/10.1016/j.compbiolchem.2019.05.013
        quote: S Banerjee, <b>A Roy</b>, MS Madhusudhan, HR Bairagya, A Roy | Computational Biology and Chemistry | October 2019
        # description: | # this will include new lines to allow paragraphs
        #   Upcoming

      - layout: top-middle
        border: weak
        title: Protein Interaction Z Score Assessment (PIZSA) - an empirical scoring scheme for evaluation of protein–protein interactions
        link: https://doi.org/10.1093/nar/gkz368
        link_text: doi.org/10.1093/nar/gkz368
        additional_links:
          - title: https://doi.org/10.1093/nar/gkz368
            icon: fas fa-book
            url: https://doi.org/10.1093/nar/gkz368
        quote: <b>AA Roy</b>*, AS Dhawanjewar*, P Sharma, G Singh, MS Madhusudhan | Nucleic Acids Research | July 2019
        # description: | # this will include new lines to allow paragraphs
        #   Upcoming

      - layout: top-middle
        border: weak
        title: <i>In silico</i> methods for design of biological therapeutics
        link: https://doi.org/10.1016/j.ymeth.2017.09.008
        link_text: doi.org/10.1016/j.ymeth.2017.09.008
        additional_links:
          - title: https://doi.org/10.1016/j.ymeth.2017.09.008
            icon: fas fa-book
            url: https://doi.org/10.1016/j.ymeth.2017.09.008
        quote: <b>A Roy</b>*, S Nair*, N Sen, N Soni, MS Madhusudhan | Methods | December 2017
        # description: | # this will include new lines to allow paragraphs
        #   Upcoming

      - layout: top-middle
        title: Gustatory receptors in Lepidoptera - chemosensation and beyond
        link: https://doi.org/10.1111/imb.12246
        link_text: doi.org/10.1111/imb.12246
        additional_links:
          - title: https://doi.org/10.1111/imb.12246
            icon: fas fa-book
            url: https://doi.org/10.1111/imb.12246
        quote: AR Agnihotri, <b>AA Roy</b>, RS Joshi | Insect Molecular Biology | May 2016
        # description: | # this will include new lines to allow paragraphs
        #   Upcoming

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Institute of Bioinformatics and Biotechnology
        caption: 2011 - 2016
        sub_title: M.Sc. Biotechnology
        quote: >
          5 year integrated Master's degree at Savitribai Phule Pune University (formerly known as University of Pune).
        description: | # this will include new lines to allow paragraphs
          Multidisciplinary course with subjects including Physics, Chemistry, Biology, Mathematics and Computer Science.

      - layout: left
        title: Learning Centre
        caption: 2009 - 2011
        sub_title: Biology
        quote: >
          Learning how to learn!
        description: | # this will include new lines to allow paragraphs
          I had the opportunity to be mentored by Mr. S.L. Acharya, who instilled in me a deep passion for Science and a desire to never stop learning.

  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        # border: weak
        title: Advanced Learning Algorithms
        link: https://www.coursera.org/account/accomplishments/certificate/YQTEQLSC6MWS
        link_text: Credential ID - YQTEQLSC6MWS
        additional_links:
          - title: https://www.coursera.org/account/accomplishments/certificate/YQTEQLSC6MWS
            icon: fas fa-award
            url: https://www.coursera.org/account/accomplishments/certificate/YQTEQLSC6MWS
        quote: Artificial Neural Networks | Decision Trees | Random Forest | XGBoost
        # description: | # this will include new lines to allow paragraphs
        #   Upcoming

      - layout: top-middle
        # border: weak
        title: Linear Algebra for Machine Learning and Data Science
        link: https://www.coursera.org/account/accomplishments/certificate/MMYLBVUUUHTR
        link_text: Credential ID - MMYLBVUUUHTR
        additional_links:
          - title: https://www.coursera.org/account/accomplishments/certificate/MMYLBVUUUHTR
            icon: fas fa-award
            url: https://www.coursera.org/account/accomplishments/certificate/MMYLBVUUUHTR
        quote: Linear Algebra | Machine Learning | Eigenvalues and Eigenvectors
        # description: | # this will include new lines to allow paragraphs
        #   Upcoming

      - layout: top-middle
        # border: weak
        title: Supervised Machine Learning - Regression and Classification
        link: https://www.coursera.org/account/accomplishments/certificate/X6R5TRC94RSF
        link_text: Credential ID - X6R5TRC94RSF
        additional_links:
          - title: https://www.coursera.org/account/accomplishments/certificate/X6R5TRC94RSF
            icon: fas fa-award
            url: https://www.coursera.org/account/accomplishments/certificate/X6R5TRC94RSF
        quote: Machine Learning | Linear Regression | Logistic Regression
        # description: | # this will include new lines to allow paragraphs
        #   Upcoming

      - layout: top-middle
        # border: weak
        title: DEV290x - Computer Vision and Image Analysis
        link: https://courses.edx.org/certificates/d68173b232194e3b88f7890dcde13eab
        link_text: Credential ID - d68173b232194e3b88f7890dcde13eab
        additional_links:
          - title: https://courses.edx.org/certificates/d68173b232194e3b88f7890dcde13eab
            icon: fas fa-award
            url: https://courses.edx.org/certificates/d68173b232194e3b88f7890dcde13eab
        quote: Convolutional Neural Networks | Semantic Segmentation | Computer Vision
        # description: | # this will include new lines to allow paragraphs
        #   Upcoming

      - layout: top-middle
        # border: weak
        title: Genomic Data Science with Galaxy
        link: https://www.coursera.org/account/accomplishments/certificate/SPNMPRU8XX
        link_text: Credential ID - SPNMPRU8XX
        additional_links:
          - title: https://www.coursera.org/account/accomplishments/certificate/SPNMPRU8XX
            icon: fas fa-award
            url: https://www.coursera.org/account/accomplishments/certificate/SPNMPRU8XX
        quote: Galaxy | Genomic Analysis
        # description: | # this will include new lines to allow paragraphs
        #   Upcoming

      - layout: top-middle
        # border: weak
        title: Python for Genomic Data Science
        link: https://www.coursera.org/account/accomplishments/certificate/PE6N7DWB27
        link_text: Credential ID - PE6N7DWB27
        additional_links:
          - title: https://www.coursera.org/account/accomplishments/certificate/PE6N7DWB27
            icon: fas fa-award
            url: https://www.coursera.org/account/accomplishments/certificate/PE6N7DWB27
        quote: Python | Biopython | Bioinformatics | Genomics
        # description: | # this will include new lines to allow paragraphs
        #   Upcoming

      - layout: top-middle
        # border: weak
        title: Introduction to Genomic Technologies
        link: https://www.coursera.org/account/accomplishments/certificate/E6CBDEAKHF
        link_text: Credential ID - E6CBDEAKHF
        additional_links:
          - title: https://www.coursera.org/account/accomplishments/certificate/E6CBDEAKHF
            icon: fas fa-award
            url: https://www.coursera.org/account/accomplishments/certificate/E6CBDEAKHF
        quote: Next Generation Sequencing | Bioinformatics | Statistics
        # description: | # this will include new lines to allow paragraphs
        #   Upcoming

  - title: When I'm not in the lab
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
